build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'KtFileCountProcessor'
  # - 'DependencyProcessor'
  # - 'LinesOfCodeProcessor'
  # - 'MethodCountProcessor'
  # - 'SourceCodeStatsProcessor'

console-reports:
  active: true
  exclude:
     - 'ProjectStatisticsReport'
     - 'ComplexityReport'
     - 'NotificationReport'
     - 'FindingsReport'
     - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
  # - 'TxtOutputReport'
  # - 'XmlOutputReport'
  # - 'HtmlOutputReport'
  # - 'MdOutputReport'

comments:
  active: true
  
complexity:
  active: true
  CyclomaticComplexMethod:
    threshold: 20
  LongMethod:
    threshold: 100
  TooManyFunctions:
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 7
  ComplexCondition:
    threshold: 4

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: false

performance:
  active: true
  SpreadOperator:
    active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers: ['-1', '0', '1', '2']
  UnusedPrivateMember:
    active: true
  ReturnCount:
    active: true
    max: 2
    excludeGuardClauses: true
